---
title: "Regression Tree and SVM Model"
author: "Brian"
date: "2022-11-22"
output: html_document
---

## Including Libraries
```{r, include=FALSE}
library(tidyverse)
library(readr)
library(caret)
library(ggplot2)
library(dplyr)
library(e1071)
library(tidyr)
library(knitr)
library(rpart)
library(rattle)
library(rpart.plot)
library(arules)
library(Metrics)

```

# Importing Data
```{r}
# Download Test and Training data
set.seed(2)
movie_test <- read_csv('movie_test.csv', trim_ws = TRUE)
movie_train <- read_csv('movie_train.csv', trim_ws = TRUE)
movie_dataset <- read_csv('movies_train_test.csv', trim_ws = TRUE)
```

# Budget Preprocessing and Set Up
```{r, echo = True}
#Plot graphs of 
ggplot(movie_train, aes(budget)) + geom_histogram()


#Discretize the Budget for classification into equal frequency after trimming
#Breaks into 3 parts:
#Low_Budget = 1 Dollar - 8.85 Million
#Middle_Budget = 8.85 Million - 35 Million
#High_Budget = 35 Million - 800 Million
disc.budget <- discretizeDF(movie_train, methods = list(
  budget = list(method = "frequency", breaks = 3,
    labels = c("Low_Budget", "Middle_Budget", "High_Budget"))
  ),
  default = list(method = "none")
  )


#Create tables for different models removing response variables
model_movie_train <- subset(movie_train, 
                            select = -c(revenue, vote_average, vote_count))
model_movie_test <- subset(movie_test, 
                           select = -c(revenue, vote_average, vote_count))



```


# Training Data on Voter Average
```{r}
#Create tables for different models
VA.model_movie_train <- subset(movie_train, 
                            select = -c(revenue, vote_count))
#Voter Average on Training Data
va1 <- rpart(
  formula = vote_average ~.,
  data    = VA.model_movie_train,
  )
va1
fancyRpartPlot(va1, main = "Vote_Average")

```

# Testing Voter Average model on Test Data 
```{r}
#Display the results
printcp(va1)

#Visualize cross-validation results
plotcp(va1)

#Summary of models:
#If no value comes from model, no impact towards the outcome. write in report
#Don't use profit as predictor

#Prune trees
pva1 <- prune(va1, cp = 0.052051) 
pva2 <- prune(va1, cp = 0.017867) 

#Plot Pruned Tree
#On Cleaned Budget Data
fancyRpartPlot(pva1,
               main = "VOTER AVERAGE", 
               sub = "cp = 0.052")
fancyRpartPlot(pva2, 
               main = "VOTER AVERAGE", 
               sub = "cp = 0.018")


train.pred.va1 <- predict(pva1, movie_train)
train.pred.va2 <- predict(pva2, movie_train)

test.pred.va1 <- predict(pva1, movie_test)
test.pred.va2 <- predict(pva2, movie_test)

pred.va1 <- predict(pva1, movie_dataset)
pred.va2 <- predict(pva2, movie_dataset)

#Training Data Accuracy
#Model 2 has the best Mean Absolute Error of 0.72
MAE(movie_train$vote_average, train.pred.va1)
MAE(movie_train$vote_average, train.pred.va2)

#Model 2 has the best Root Mean Square Error of 0.99
RMSE(movie_train$vote_average, train.pred.va1)
RMSE(movie_train$vote_average, train.pred.va2)

#Model 2 has the best Relative Absolute Error of 0.93
rae(movie_train$vote_average, train.pred.va1)
rae(movie_train$vote_average, train.pred.va2)

#Test Data Accuracy
#Model 2 has the best Mean Absolute Error of 0.72
MAE(movie_test$vote_average, test.pred.va1)
MAE(movie_test$vote_average, test.pred.va2)

#Model 2 has the best Root Mean Square Error of 0.98
RMSE(movie_test$vote_average, test.pred.va1)
RMSE(movie_test$vote_average, test.pred.va2)

#Model 2 has the best Relative Absolute Error of 0.91
rae(movie_test$vote_average, test.pred.va1)
rae(movie_test$vote_average, test.pred.va2)

#Actual Data Accuracy
#Model 2 has the best Mean Absolute Error of 0.72
MAE(movie_dataset$vote_average, pred.va1)
MAE(movie_dataset$vote_average, pred.va2)

#Model 2 has the best Root Mean Square Error of 0.99
RMSE(movie_dataset$vote_average, pred.va1)
RMSE(movie_dataset$vote_average, pred.va2)

#Model 2 has the best Relative Absolute Error of 0.92
rae(movie_dataset$vote_average, pred.va1)
rae(movie_dataset$vote_average, pred.va2)

#Use Model 2
fancyRpartPlot(pva2, 
               main = "VOTER AVERAGE", 
               sub = "")

```
