---
title: "svm_data"
author: "Kyra Hendrickson"
date: "2022-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r} 
# uploads
library(tidyverse)
library(readr)
library(DataExplorer)
library(plotly)
library(caret)
library(ggplot2)
library(dplyr)
library(MASS) 
library(reshape2) 
```

```{r}
# download test and training data
names = c('budget','revenue','runtime','vote_average','vote_count','en','hu','fr','ru','es','Action','Comedy','Drama','Romance','Thriller','Dwayne.Johnson','Samuel.L..Jackson','Tom.Hanks','Johnny.Depp','Harrison.Ford','Denzel.Washington',	'Morgan.Freeman',	'Robert.De.Niro',	'Bruce.Willis',	'Meryl.Streep',	'Robert.Downey.Jr.',	'Tom.Cruise',	'Warner.Bros',	'Universal',	'X20th.Century.Fox',	'Paramount',	'Columbia' ,	'Pixar',	'Marvel', 	'Walt.Disney')

movie_train <- read_csv('movie_train.csv', col_names=names, trim_ws = TRUE, show_col_types = FALSE)[-c(1), ]
movie_test <- read_csv('movie_test.csv', col_names=names, trim_ws = TRUE, show_col_types = FALSE)[-c(1), ]
```

```{r}
## Create ratio indicator column

# create net revenue col
movie_train$budget <- as.numeric(movie_train$budget)
movie_train$revenue <- as.numeric(movie_train$revenue)
movie_train$net.revenue <- (movie_train$revenue - movie_train$budget)

movie_test$budget <- as.numeric(movie_test$budget)
movie_test$revenue <- as.numeric(movie_test$revenue)
movie_test$net.revenue <- (movie_test$revenue - movie_test$budget)

# create revenue/budget ratio col, this is our indicator variable
movie_train$ratio <- abs(movie_train$net.revenue/movie_train$budget)
movie_test$ratio <- abs(movie_test$net.revenue/movie_test$budget)

# create a new col as indicator col, need to seperate ratio into <1 and >1
movie_train$ratio_indicator<-factor(ifelse(movie_train$ratio<1,"No.Profit","Profit"))
movie_test$ratio_indicator<-factor(ifelse(movie_test$ratio<1,"No.Profit","Profit"))
```

```{r}
## Turn studio into numerical attribute, get one column 

## training set
melt_train <- melt(movie_train, id = c('budget','revenue','runtime','vote_average','vote_count','en','hu','fr','ru','es','Action','Comedy','Drama','Romance','Thriller','Dwayne.Johnson','Samuel.L..Jackson','Tom.Hanks','Johnny.Depp','Harrison.Ford','Denzel.Washington',	'Morgan.Freeman',	'Robert.De.Niro',	'Bruce.Willis',	'Meryl.Streep',	'Robert.Downey.Jr.',	'Tom.Cruise','net.revenue','ratio','ratio_indicator')) 

melt_train = melt_train[melt_train$value ==TRUE, ] # takes out duplicates by getting rid of all the FALSE values
names(melt_train)[31] = "studio" # rename 31st col studio

studio_vector_train <-unclass(melt_train$studio)

melt_train$studio_unclass <- studio_vector_train

## test data
melt_test <- melt(movie_test, id = c('budget','revenue','runtime','vote_average','vote_count','en','hu','fr','ru','es','Action','Comedy','Drama','Romance','Thriller','Dwayne.Johnson','Samuel.L..Jackson','Tom.Hanks','Johnny.Depp','Harrison.Ford','Denzel.Washington',	'Morgan.Freeman',	'Robert.De.Niro',	'Bruce.Willis',	'Meryl.Streep',	'Robert.Downey.Jr.',	'Tom.Cruise','net.revenue','ratio','ratio_indicator')) 

melt_test = melt_test[melt_test$value ==TRUE, ] # takes out duplicates by getting rid of all the FALSE values
names(melt_test)[31] = "studio" # rename 31st col studio

studio_vector_test <-unclass(melt_test$studio)

melt_test$studio_unclass <- studio_vector_test
```

```{r}
## Turn actor into numerical attribute, get one column 

melt_train2 <- melt(melt_train, id = c('budget','revenue','runtime','vote_average','vote_count','en','hu','fr','ru','es','Action','Comedy','Drama','Romance','Thriller','net.revenue','ratio','ratio_indicator','studio','value','studio_unclass')) 

names(melt_train2)[23] = "value2" # rename 23nd col studio

melt_train2 = melt_train2[melt_train2$value2 ==TRUE, ] # takes out duplicates by getting rid of all the FALSE values
names(melt_train2)[22] = "actor" # rename 22nd col studio

actor_vector_train <-unclass(melt_train2$actor)

melt_train2$actor_unclass <- actor_vector_train

## test data
melt_test2 <- melt(melt_test, id = c('budget','revenue','runtime','vote_average','vote_count','en','hu','fr','ru','es','Action','Comedy','Drama','Romance','Thriller','net.revenue','ratio','ratio_indicator','studio','value','studio_unclass')) 

names(melt_test2)[23] = "value2" # rename 23nd col studio

melt_test2 = melt_test2[melt_test2$value2 ==TRUE, ] # takes out duplicates by getting rid of all the FALSE values
names(melt_test2)[22] = "actor" # rename 22nd col studio

actor_vector_test <-unclass(melt_test2$actor)

melt_test2$actor_unclass <- actor_vector_test
```

```{r}
## Turn genre into numerical attribute, get one column 

melt_train3 <- melt(melt_train2, id = c('budget','revenue','runtime','vote_average','vote_count','en','hu','fr','ru','es','net.revenue','ratio','ratio_indicator','studio','value','studio_unclass','actor','value2','actor_unclass')) 

names(melt_train3)[21] = "value3" # rename 21th col studio

melt_train3 = melt_train3[melt_train3$value3 ==TRUE, ] # takes out duplicates by getting rid of all the FALSE values
names(melt_train3)[20] = "genre" # rename 20nd col studio

genre_vector_train <-unclass(melt_train3$genre)

melt_train3$genre_unclass <- genre_vector_train

## test data
melt_test3 <- melt(melt_test2, id = c('budget','revenue','runtime','vote_average','vote_count','en','hu','fr','ru','es','net.revenue','ratio','ratio_indicator','studio','value','studio_unclass','actor','value2','actor_unclass')) 

names(melt_test3)[21] = "value3" # rename 21th col studio

melt_test3 = melt_test3[melt_test3$value3 ==TRUE, ] # takes out duplicates by getting rid of all the FALSE values
names(melt_test3)[20] = "genre" # rename 20nd col studio

genre_vector_test <-unclass(melt_test3$genre)

melt_test3$genre_unclass <- genre_vector_test
```



```{r}
## train
svm_data1 <- subset(melt_train3, select = -c(value, value2, value3,en,hu,fr,es))
svm_data2 <- subset(melt_train3, select = -c(studio, value, actor, value2, genre, value3,en,hu,fr,es))
## test
svm_data3 <- subset(melt_test3, select = -c(value, value2, value3,en,hu,fr,es))
svm_data4 <- subset(melt_test3, select = -c(studio, value, actor, value2, genre, value3,en,hu,fr,es))
```


```{r}

data <- write_excel_csv(svm_data1, "svm_traindata_labeled.csv")
data <- write_excel_csv(svm_data2, "svm_traindata.csv")

data <- write_excel_csv(svm_data3, "svm_testdata_labeled.csv")
data <- write_excel_csv(svm_data4, "svm_testdata.csv")
```



```{r}
# create correlation matrix to decide what attribute best to use with budget
contAttrib <- svm_data2
contAttrib_numer <- data.matrix(contAttrib)

# computing correlation matrix
cor_data = cor(contAttrib_numer)
 
print("Correlation matrix")
print(cor_data)
```
** notes: 
Assuming linear correlation:
- NA on langunage since all the movies are in english
- Things that have most correlation with net.revenue:
  > Budget with a correlation of 0.67
  > Production company with a correlation of 0.18
  > Genre with a correlation of 0.15
All other attributes have a magnitude correlation <= 0.07 with net revenue

